version: "2"
services:
 vpn:
  image: wireguard:local
  volumes:
   - ./conf:/etc/wireguard
  networks:
   - net
  ports:
   - 55556:55556/udp
  restart: unless-stopped
  cap_add:
   - NET_ADMIN
   - SYS_MODULE

networks:
  net:
