version: "3.5"
services:
    vpn:
        image: kylemanna/openvpn
        # environment:
        #     OVPN_DATA: ovpn-data-sbas
    router:
        image: calico/bird
    sig:
        image: ethznetsec/scion_base
