version: "3.5"
services:
    vpn:
        image: kylemanna/openvpn
        # environment:
        #     OVPN_DATA: ovpn-data-sbas
    router:
        build: peering/
        command: tail -F keep-alive
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
        cap_add:
            - NET_ADMIN
        devices:
            - "/dev/net/tun"