#!/bin/bash

sudo apt update
sudo apt install -y \
    scion-sig \
    wireguard

sudo pip3 install mrtparse
sudo pip3 install pyroute2

# Install BIRD 2.0.8 manually
# It is necessary to have at least version 2.0.8. Older versions do not support the necessary features for SBAS.
# At the time of writing (September 2021), v2.0.8 is not available in apt-get and needs to be compiled from the source code.
# For some reason, all features are supported only when I install v2.0.7 through apt-get and then install v2.0.8 from the repo.
# When v2.0.8 becomes available in apt-get, please replace lines below with:
# sudo apt install bird2=2.0.8
# Beginning of BIRDv2.0.8 installation
wget http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.57_all.deb
sudo dpkg -i init-system-helpers_1.57_all.deb
sudo apt install bird2

git clone https://gitlab.nic.cz/labs/bird.git
cd bird
git checkout v2.0.8
sudo apt install -y autoconf
autoreconf
sudo apt-get install -y flex
sudo apt-get install -y bison
sudo apt-get install -y libreadline-dev
./configure --prefix=/usr --sysconfdir=/etc/bird --runstatedir=/run/bird
make
sudo make install

cd ..
# End of BIRDv2.0.8 installation
